<?php

namespace app\models;

use Phalcon\Mvc\Model;

/**
 * Rehersals
 * 
 * @package app\models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-07-23, 02:54:26
 */
class Rehersals extends Model
{

    /**
     *
     * @var integer
     */
    public $id;

    /**
     *
     * @var integer
     */
    public $page_id;

    /**
     *
     * @var string
     */
    public $location;

    /**
     *
     * @var string
     */
    public $scheduled_at;

    /**
     *
     * @var string
     */
    public $note;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('page_id', 'app\models\Page', 'id', array('alias' => 'page'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'rehersals';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Rehersals[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Rehersals
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
